name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Unit test with unittest
        run: | 
          python -m unittest tests/units/test_unit.py
      - name: Integration test with unittest
        run: | 
          python -m unittest tests/functional/test_courses.py
          python -m unittest tests/functional/test_job_role.py
          python -m unittest tests/functional/test_role_map.py
          python -m unittest tests/functional/test_skill.py
          python -m unittest tests/functional/test_skill_map.py
          python -m unittest tests/functional/test_course_map.py
          python -m unittest tests/functional/test_registration.py
          python -m unittest tests/functional/test_journey.py
          python -m unittest tests/functional/test_journey_map.py